print('Simple bill calculator')
print()
bill = float(input('How much did you spend?\n'))
print('--------------------------------')
tip = int(input('What % do you want to tip?\n'))
print('--------------------------------')
people = int(input('How many people?\n'))
print('--------------------------------')
bill_plus_tip = round((tip/100) * round(bill,2) + round(bill,2),2)
print('================================')
print()
print('You all owe',bill_plus_tip,'Plus Tip')
print()
print('================================')
print('++++++++++++++++++++++++++++++++')
print()
print(round(bill_plus_tip / people,2),'to split between you')
print()
print('++++++++++++++++++++++++++++++++')